
#https://www.youtube.com/watch?v=xBplLm9A9NM&list=PLVuSm3M08bkzNY-nSCS9TQDILVrCkSvfX&index=4
project_id: frank--opentofu-project-800
project_name: "FrankOpenTOFUProject"
region: us-central1
billing_account:
sa_name:  frank-tofu-sa-800  # Service Account name
sa_name:  frank-tofu-sa-800.json  # Service Account key

apis:
- iam.googleapis.com
- compute.googleapis.com
- cloudbuild.googleapis.com
- run.googleapis.com
- artifactregistry.googleapis.com
- cloudfunctions.googleapis.com
